### ISSUE TITLE
Inappropriate events in calendar

### ISSUE THREAD

**Issue by mavit** [BirminghamIO/calendar.birmingham.io#15]
Personal-looking events like "Meet florist" and "Gemma half marathon" have started creeping into the 
birmingham.io calendar.  Can we tell where they're coming from?  Does someone have their personal calendar misconfigured?

**Comment by rythie** [comment]
I had a look, it's from the Midlands Indies Google Calendar. However, they are on meetup anyway, so it's duplicated anyway. Could just remove it?

**Comment by stuartlangridge** [comment]
I'll ping the brumindies crowd and ask.

**Comment by stuartlangridge** [comment]
COmmitted a change to remove it. I'm not sure if this removes _existing_ wrong events from the calendar, though; @rythie we might need to go in and delete those by hand?

**Comment by rythie** [comment]
Not sure, you wrote the code!

**Comment by stuartlangridge** [comment]
Yeah, I know :) My thought is: we'll leave it until tomorrow, by which time the calendar will have had ample time to run a few generations and clear itself out. If it hasn't done so by tomorrow I'll remove the incorrect events by hand, if I can remember how to sign into the calendar's account :-)

**Comment by stuartlangridge** [comment]
I believe these events are now all caught up with and removed, so I'll close this. If I've missed any, please shout and I'll clean them up by hand!
